### ISSUE TITLE
webpack: Failed to compile.

### ISSUE THREAD

**Issue by tomasmcm** [ptboyer/rymd#1]
It seems there is something missing, maybe some env settings for webpack?

```
ERROR in ./src/app.js
Module build failed: SyntaxError: Unexpected token, expected , (57:31)
```

Can you help? thanks

**Comment by ptboyer** [comment]
Hey @tomasmcm thanks for expressing interest! Turns out I hastily committed the project after working on it and the three.js example that I worked from had a misleading set of `.gitignore` rules, so the `.babelrc` was excluded from being committed. So I took this opportunity to clean up a bit. Feel free to fork and play around with it. Would be great to see this built up a bit more if you want to contribute with a PR at some point. Cheers!
